# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YV1Bvb4NiR06UbDTIiR8fZ1kqiAO48_Q
"""

# GİRİŞ

Türkiye, dünyanın en aktif deprem kuşaklarından biri üzerinde yer almakta olup tarih boyunca birçok yıkıcı deprem yaşamıştır. Ülkenin büyük bir bölümü, özellikle Kuzey Anadolu Fay Hattı, Doğu Anadolu Fay Hattı ve Batı Anadolu Fay Sistemi üzerinde bulunduğundan deprem riski taşımaktadır. Bu nedenle deprem verilerinin analiz edilmesi, geçmişte meydana gelen sismik hareketlerin incelenmesi ve gelecekte alınabilecek önlemlerin belirlenmesi açısından büyük önem taşımaktadır.

Günümüzde veri bilimi ve veri analizi teknikleri, büyük veri kümelerinin anlamlı bilgilere dönüştürülmesini sağlayarak doğal afetlerin daha iyi anlaşılmasına katkı sunmaktadır. Deprem verilerinin istatistiksel yöntemler ve görselleştirme teknikleri ile incelenmesi, depremlerin zamansal ve mekânsal dağılımlarının ortaya çıkarılmasına yardımcı olmaktadır.

Bu çalışmada, 1915-2021 yılları arasında Türkiye'de meydana gelen depremlere ait veri seti kullanılmıştır. Veri seti üzerinde öncelikle veri temizleme ve ön işleme adımları uygulanmış, ardından deprem büyüklüğü, derinliği, gerçekleşme zamanı ve konum bilgileri analiz edilmiştir. Elde edilen veriler çeşitli grafikler yardımıyla görselleştirilerek yorumlanmış ve Türkiye'deki deprem faaliyetleri hakkında genel bir değerlendirme yapılmıştır.

Çalışmanın amacı, Python programlama dili ve veri analizi kütüphaneleri kullanılarak deprem verilerinin nasıl işlenebileceğini göstermek ve elde edilen sonuçlar doğrultusunda Türkiye'nin deprem dağılımı hakkında anlamlı çıkarımlar yapmaktır.

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('/content/turkey_earthquakes(1915-2021).csv',sep=';')
print(df.head())

print(df.info())
print(df.isnull().sum())

silinecekler=['No','Deprem Kodu','Tip','MD','ML','Mw','Ms','Mb',]
df_temiz=df.drop(columns=silinecekler)
df_temiz.head()

df_temiz['Olus tarihi']=pd.to_datetime(df_temiz['Olus tarihi'])
df_temiz['Olus zamani_dt']=pd.to_datetime(df_temiz['Olus zamani'],format='%H:%M:%S.%f',errors='coerce')
df_temiz.dropna(subset=['Olus zamani_dt'],inplace=True)
df_temiz['Olus zamani']=df_temiz['Olus zamani_dt'].dt.time
df_temiz['Yil']=df_temiz['Olus tarihi'].dt.year
df_temiz['Ay']=df_temiz['Olus tarihi'].dt.month
df_temiz=df_temiz.dropna(subset=['Olus tarihi'])
df_temiz['Yil']=df_temiz['Yil'].astype(int)
df_temiz['Ay']=df_temiz['Ay'].astype(int)

df_temiz.head()

import re
def il_ayıkla(metin):
    if pd.isna(metin):
      return "BİLİNMEYEN"

    parantez_ici=re.search(r'\((.*?)\)',str(metin))

    if parantez_ici:
      konum=parantez_ici.group(1).strip()
      if any(kelime in konum for kelime in["AKDENIZ","EGE DENIZI","KARADENIZ","MARMARA"]):
        return "DENİZ /KÖRFEZ"
      return konum

    else:
      metin_temiz=re.sub(r'\([^()]*\)', '', str(metin))

      return "metin_temiz"
df_temiz['Temiz_Il']=df_temiz['Yer'].apply(il_ayıkla)
df_temiz[['Yer','Temiz_Il','Yil','Ay']].head()

df_nihai__gorunum=df_temiz[['Olus tarihi','Olus zamani','Enlem','Boylam','Derinlik','xM','Yer','Yil','Ay','Temiz_Il']]

df_nihai__gorunum.head(50)

en_buyukler = df_nihai__gorunum.groupby("Yil")["xM"].max()

plt.figure(figsize=(12,6))
plt.plot(en_buyukler.index,
         en_buyukler.values,
         marker="o")

plt.title("Yıllara Göre En Büyük Deprem")
plt.xlabel("Yıl")
plt.ylabel("Maksimum Büyüklük")
plt.grid()
plt.show()

aylik_deprem = df_nihai__gorunum.groupby("Ay").size()

plt.figure(figsize=(8,5))
aylik_deprem.plot(kind="bar")
plt.title("Aylara Göre Deprem Sayısı")
plt.xlabel("Ay")
plt.ylabel("Deprem Sayısı")
plt.show()

EN FAZLA DEPREM HANGİ İLLERDE GÖRÜLMÜŞTÜR

ilk10 = df_nihai__gorunum["Temiz_Il"].value_counts().head(10)

plt.figure(figsize=(8,8))
plt.pie(ilk10,
        labels=ilk10.index,
        autopct='%1.1f%%')

plt.title("Depremlerin İllere Göre Dağılımı")
plt.show()

DEPREM BÜYÜKLÜKLERİNİN DAĞILIMI NASILDIR ?

plt.figure(figsize=(10,6))
plt.hist(df_nihai__gorunum["xM"], bins=30)
plt.title("Deprem Büyüklüğü Dağılımı")
plt.xlabel("Büyüklük")
plt.ylabel("Frekans")
plt.show()

plt.figure(figsize=(10,6))
plt.hist(df_nihai__gorunum["Derinlik"], bins=30)
plt.title("Deprem Derinlikleri Dağılımı")
plt.xlabel("Derinlik (km)")
plt.ylabel("Frekans")
plt.show()

plt.figure(figsize=(10,6))
plt.scatter(df_nihai__gorunum["Derinlik"],
            df_nihai__gorunum["xM"],
            alpha=0.4)

plt.title("Derinlik ve Büyüklük İlişkisi")
plt.xlabel("Derinlik")
plt.ylabel("Büyüklük")
plt.show()

yillik = df_nihai__gorunum.groupby("Yil").size()

rolling = yillik.rolling(5).mean()

plt.figure(figsize=(12,6))
plt.plot(yillik.index, yillik.values, alpha=0.4)
plt.plot(rolling.index, rolling.values)

plt.title("Deprem Sayısının Uzun Dönemli Eğilimi")
plt.xlabel("Yıl")
plt.ylabel("Deprem Sayısı")
plt.show()

# SONUÇ VE DEĞERLENDİRME

Bu çalışmada, 1915-2021 yılları arasında Türkiye'de meydana gelen deprem verileri üzerinde veri ön işleme, temizleme, analiz ve görselleştirme işlemleri gerçekleştirilmiştir. Veri setindeki eksik ve gereksiz sütunlar temizlenmiş, tarih ve saat verileri uygun formata dönüştürülmüş, ayrıca deprem konum bilgileri düzenlenerek analiz için kullanılabilir hale getirilmiştir.

Yapılan analizler sonucunda deprem sayılarının yıllara göre değişim gösterdiği, bazı dönemlerde kayıt altına alınan deprem sayılarında belirgin artışlar olduğu gözlemlenmiştir. Bu artışların bir kısmının teknolojik gelişmeler ve ölçüm sistemlerinin yaygınlaşmasıyla ilişkili olabileceği değerlendirilmiştir.

Aylara göre yapılan incelemede depremlerin yılın tüm aylarında meydana geldiği ve belirgin bir mevsimsel dağılım göstermediği görülmüştür. İllere göre yapılan analizlerde ise aktif fay hatları üzerinde bulunan bölgelerde deprem yoğunluğunun daha yüksek olduğu tespit edilmiştir.

Deprem büyüklüklerinin dağılımı incelendiğinde, düşük ve orta büyüklükteki depremlerin oldukça sık gerçekleştiği, yüksek büyüklüklü depremlerin ise daha nadir meydana geldiği görülmüştür. Derinlik analizleri, depremlerin büyük çoğunluğunun sığ odaklı olduğunu göstermiştir. Ayrıca deprem büyüklüğü ile derinlik arasında güçlü bir ilişki bulunmadığı gözlemlenmiştir.

Sonuç olarak bu çalışma, Python veri bilimi araçları kullanılarak büyük ölçekli deprem verilerinin nasıl işlenebileceğini, analiz edilebileceğini ve görselleştirilebileceğini göstermektedir. Elde edilen bulgular, Türkiye'nin deprem gerçeğini ortaya koyarken veri analizi yöntemlerinin doğal afetlerin incelenmesinde ne kadar etkili olduğunu da göstermektedir.